### ISSUE TITLE
Simplify `isPowerOf2`

### ISSUE THREAD

**Issue by yoheioka** [LayerXcom/stark-sol#27]
I was reading through the code and noticed that `isPowerOf2()` in `Verifier.sol` can be simplified as the following:

```
function isPowerOf2(uint _x) internal pure returns (bool) {
    return _x > 0 && (_x & (_x - 1) == 0);
}
```

I'm not sure by how much, but it may be more optimal when `_x` is a large number.

**Comment by osuketh** [comment]
thanks! LGTM. I'll fix it.
